---
# Usage: http://ruhoh.com/usage/configure/ 

RuhohSpec: '1.0'
theme : readmore
production_url : http://www.readmore.ch

posts:
  permalink: /:categories/:title/
  summary_lines: 20
  latest: 10

pages:
  permalink: 'pretty'
