title : ReadMore
tagline: Blog Tagline
author : 
  name : Stefan "Odi" Oderbolz
  email : odi@readmore.ch
  github : odi86
  twitter : odi

navigation :
  - archive.html
  - tags.html
  - about.md
  
